import Link from 'next/link';
import { PageHeader, StatCard, SectionCard, Badge } from '@/components/ui';
import { safeCount } from '@/lib/data';
import { Users, FolderKanban, WalletCards, Building2, Plus, UserPlus, ClipboardList, FileSignature, Calculator, House, Workflow, Landmark } from 'lucide-react';
export default async function Page(){
 const [leads,transactions,agents,payouts,trust]=await Promise.all([safeCount('leads'),safeCount('transactions'),safeCount('profiles'),safeCount('agent_payouts'),safeCount('trust_deposits')]);
 return <><PageHeader title="Dashboard" description="Your brokerage command centre: leads, deals, trust, commissions, compliance and agent activity." action={<Link href="/transactions/new" className="btn primary"><Plus size={16}/>New transaction</Link>}/>
 <div className="stats-grid"><StatCard label="CRM leads" value={leads} icon={Users} hint="Live Supabase count"/><StatCard label="Transactions" value={transactions} icon={FolderKanban}/><StatCard label="Agents" value={agents} icon={Building2}/><StatCard label="Trust deposits" value={trust} icon={Landmark}/></div>
 <div className="grid-2"><SectionCard title="Quick actions" description="Common tasks in one click"><div className="quick-grid two"><Link className="quick-card" href="/crm"><span className="icon-box"><UserPlus size={19}/></span><span><strong>Add / manage lead</strong><p>CRM, tags, source and follow-up.</p></span></Link><Link className="quick-card" href="/open-houses"><span className="icon-box"><House size={19}/></span><span><strong>Open house</strong><p>Visitor registration and automatic lead capture.</p></span></Link><Link className="quick-card" href="/transactions"><span className="icon-box"><ClipboardList size={19}/></span><span><strong>Transaction file</strong><p>Listing or buyer-side workflow.</p></span></Link><Link className="quick-card" href="/back-office"><span className="icon-box"><FileSignature size={19}/></span><span><strong>Back office review</strong><p>CRI, trust, commission and completion.</p></span></Link></div></SectionCard>
 <SectionCard title="Attention queue" description="Items that should not get lost"><div className="card-list"><div className="list-row"><div><strong>Trust verification</strong><small>Confirm money actually reached trust before release.</small></div><Badge tone="warning">Review</Badge></div><div className="list-row"><div><strong>Commission + 5% GST</strong><small>Stored separately from agent deductions.</small></div><Badge tone="info">Calculated</Badge></div><div className="list-row"><div><strong>Lawyer / CRI</strong><small>Agent prepares, back office approves and sends.</small></div><Badge>Workflow</Badge></div><div className="list-row"><div><strong>Reconciliation</strong><small>Close files only after documents and money match.</small></div><Badge tone="success">Controlled</Badge></div></div></SectionCard></div>
 <SectionCard title="Lead → money → audit" description="The operating flow RealVolt is built around"><div className="quick-grid"><div className="quick-card"><span className="icon-box"><Users size={19}/></span><span><strong>Lead → Client</strong><p>CRM, forms, Meta, Google and open-house capture.</p></span></div><div className="quick-card"><span className="icon-box"><FolderKanban size={19}/></span><span><strong>Client → Transaction</strong><p>Listing or buyer-side deal without retyping data.</p></span></div><div className="quick-card"><span className="icon-box"><Calculator size={19}/></span><span><strong>Trust → Commission</strong><p>Deposit, GST, splits, fees and payout.</p></span></div><div className="quick-card"><span className="icon-box"><Workflow size={19}/></span><span><strong>Audit → Closed</strong><p>Reconcile, lock, archive and preserve history.</p></span></div></div></SectionCard>
 <div className="stats-grid"><StatCard label="Payout records" value={payouts} icon={WalletCards}/></div></>;
}