"use client";
import Link from "next/link";
import { useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

export default function SignupPage(){
 const [form,setForm]=useState({name:"",email:"",password:"",accountType:"agent"}); const [msg,setMsg]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault(); setMsg(""); try{const supabase=createSupabaseBrowserClient(); const site=process.env.NEXT_PUBLIC_SITE_URL || window.location.origin; const {error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{emailRedirectTo:`${site}/auth/callback?next=/onboarding`,data:{full_name:form.name,account_type:form.accountType}}}); if(error){setMsg(error.message);return;} setMsg("Account created. Email verification can be enabled in Supabase Auth when you are ready.");}catch(err){setMsg(err instanceof Error?err.message:"Unable to sign up");}}
 return <div className="auth-wrap"><div className="auth-side"><div className="brand"><span className="brand-badge">RV</span>RealVolt</div><h1>Start with CRM. Grow into the full brokerage OS.</h1><p style={{color:"#94a3b8",fontSize:18,lineHeight:1.7}}>Create an individual, team or brokerage workspace. Feature access can be controlled by subscription later.</p></div><div className="auth-panel"><form className="auth-card" onSubmit={submit}><h2>Create your account</h2><div className="field"><label>Name</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div className="field"><label>Email</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div className="field"><label>Password</label><input className="input" type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></div><div className="field"><label>I am signing up as</label><select className="select" value={form.accountType} onChange={e=>setForm({...form,accountType:e.target.value})}><option value="agent">Individual Realtor</option><option value="team">Team</option><option value="brokerage">Brokerage</option></select></div>{msg?<p className="muted">{msg}</p>:null}<button className="btn btn-primary" style={{width:"100%"}}>Create account</button><p className="muted">Already have an account? <Link href="/login"><b>Log in</b></Link></p></form></div></div>
}
